/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ActivityLogRouteImport } from './routes/activity-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeBaseIndexRouteImport } from './routes/knowledge-base.index'
import { Route as KnowledgeBaseDocumentIdRouteImport } from './routes/knowledge-base.$documentId'
import { Route as ExceptionsExceptionIdRouteImport } from './routes/exceptions.$exceptionId'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseIndexRoute = KnowledgeBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeBaseRoute,
} as any)
const KnowledgeBaseDocumentIdRoute = KnowledgeBaseDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => KnowledgeBaseRoute,
} as any)
const ExceptionsExceptionIdRoute = ExceptionsExceptionIdRouteImport.update({
  id: '/exceptions/$exceptionId',
  path: '/exceptions/$exceptionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/audit': typeof AuditRoute
  '/knowledge-base': typeof KnowledgeBaseRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppliers': typeof SuppliersRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/knowledge-base/$documentId': typeof KnowledgeBaseDocumentIdRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/audit': typeof AuditRoute
  '/notifications': typeof NotificationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppliers': typeof SuppliersRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/knowledge-base/$documentId': typeof KnowledgeBaseDocumentIdRoute
  '/knowledge-base': typeof KnowledgeBaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/audit': typeof AuditRoute
  '/knowledge-base': typeof KnowledgeBaseRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppliers': typeof SuppliersRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/knowledge-base/$documentId': typeof KnowledgeBaseDocumentIdRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-log'
    | '/audit'
    | '/knowledge-base'
    | '/notifications'
    | '/sitemap.xml'
    | '/suppliers'
    | '/exceptions/$exceptionId'
    | '/knowledge-base/$documentId'
    | '/knowledge-base/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-log'
    | '/audit'
    | '/notifications'
    | '/sitemap.xml'
    | '/suppliers'
    | '/exceptions/$exceptionId'
    | '/knowledge-base/$documentId'
    | '/knowledge-base'
  id:
    | '__root__'
    | '/'
    | '/activity-log'
    | '/audit'
    | '/knowledge-base'
    | '/notifications'
    | '/sitemap.xml'
    | '/suppliers'
    | '/exceptions/$exceptionId'
    | '/knowledge-base/$documentId'
    | '/knowledge-base/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogRoute: typeof ActivityLogRoute
  AuditRoute: typeof AuditRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuppliersRoute: typeof SuppliersRoute
  ExceptionsExceptionIdRoute: typeof ExceptionsExceptionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log': {
      id: '/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base/': {
      id: '/knowledge-base/'
      path: '/'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof KnowledgeBaseIndexRouteImport
      parentRoute: typeof KnowledgeBaseRoute
    }
    '/knowledge-base/$documentId': {
      id: '/knowledge-base/$documentId'
      path: '/$documentId'
      fullPath: '/knowledge-base/$documentId'
      preLoaderRoute: typeof KnowledgeBaseDocumentIdRouteImport
      parentRoute: typeof KnowledgeBaseRoute
    }
    '/exceptions/$exceptionId': {
      id: '/exceptions/$exceptionId'
      path: '/exceptions/$exceptionId'
      fullPath: '/exceptions/$exceptionId'
      preLoaderRoute: typeof ExceptionsExceptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeBaseRouteChildren {
  KnowledgeBaseDocumentIdRoute: typeof KnowledgeBaseDocumentIdRoute
  KnowledgeBaseIndexRoute: typeof KnowledgeBaseIndexRoute
}

const KnowledgeBaseRouteChildren: KnowledgeBaseRouteChildren = {
  KnowledgeBaseDocumentIdRoute: KnowledgeBaseDocumentIdRoute,
  KnowledgeBaseIndexRoute: KnowledgeBaseIndexRoute,
}

const KnowledgeBaseRouteWithChildren = KnowledgeBaseRoute._addFileChildren(
  KnowledgeBaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogRoute: ActivityLogRoute,
  AuditRoute: AuditRoute,
  KnowledgeBaseRoute: KnowledgeBaseRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuppliersRoute: SuppliersRoute,
  ExceptionsExceptionIdRoute: ExceptionsExceptionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
